<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Previous_carousel-control-next-icon</name>
   <tag></tag>
   <elementGuidId>96345cfa-ff66-470e-af8c-d2752de6e259</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.carousel-control-next-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='carouselExampleIndicators']/a[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9b8ed6fe-e205-4d60-9ee3-cecec59b5ac1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>carousel-control-next-icon</value>
      <webElementGuid>72166475-a0f9-4b1c-aacc-bf67ec2c3935</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d387af33-b38e-4d6b-8973-87167f3e81de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;carouselExampleIndicators&quot;)/a[@class=&quot;carousel-control-next&quot;]/span[@class=&quot;carousel-control-next-icon&quot;]</value>
      <webElementGuid>292afbd2-b043-4e10-b4f5-c089fa8ce253</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='carouselExampleIndicators']/a[2]/span</value>
      <webElementGuid>ab72eef9-dff5-4215-9794-fac1dcf75dce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/span</value>
      <webElementGuid>e2c77fbf-86e7-47aa-88e0-602f893cdcde</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
